mysql:
  image: mysql:5.7
  ports:
  - "1337:3307"
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_PASSWORD: root
  volumes:
  - ../../var/lib/mysql:/var/lib/mysql
  - ./my.cnf:/etc/mysql/conf.d/my.cnf
